server:
  port: 8989
  servlet:
    context-path: /users

spring:
  application:
    name: users
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootvue?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 980107sy

mybatis:
  mapper-locations: classpath:com/sunyun/mapper/*.xml
  type-aliases-package: com.sunyun.entity
